### PR TITLE
Update to adapter 1.0.1 (web extension support and other improvements)

### PR DESCRIPTION
**Pull request by jonahgraham**
Includes:

- Refactor code to allow web extension
  - https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/328
- Improved handling of ContinuedEvent
  - https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/335
- Ensure 'interrupt' and 'disconnect' signals are sent before '-gdb-exit'
  - https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/338
- Add API to pause target and wait for debugger to be suspended
  - https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/339

### CODE REVIEW

**Comment by jonahgraham** [comment]
This is a draft because it is depending on a "next" tagged cdt-gdb-adapter. Once we are convinced that we haven't regressed the adapter with the refactoring we can publish a "latest" tagged version and update/merge this PR.

**Comment by Luke-zhang-mchp** [comment]
Hey @jonahgraham, what's the estimate for getting this change published? We were hoping to get the changes from https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/issues/295 in by the end of the year. I did some testing on our IDE with the main branch of the adapter, and it works fine (obviously not definitive).

If there's anything I can do to help let me know. Alternatively I could make the same changes to target a 0.x.x release in the adapter.

**Comment by jonahgraham** [comment]
@Luke-zhang-mchp  I think we are probably good to progress this one too, between you and Renesas using it we are probably ok with the big refactor mentioned in the OP.

**Comment by jonahgraham** [comment]
The HEAD commit of the gdb adapter needs to be published as "latest" and then we can progress. I'll do that in the coming days.

**Comment by jonahgraham** [comment]
I was out sick last week - catching up now, but hopefully normal service will resume soon. Sorry for the delay.

**Comment by Luke-zhang-mchp** [comment]
Oh yeah no problem, take it easy.

**Comment by jonahgraham** [comment]
I'm working on this now.

**Comment by jonahgraham** [comment]
I updated the description to reflect what is included now as follows:


Update to adapter 1.0.1 (web extension support and other improvements)

Includes:

- Refactor code to allow web extension
  - https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/328
- Improved handling of ContinuedEvent
  - https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/335
- Ensure 'interrupt' and 'disconnect' signals are sent before '-gdb-exit'
  - https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/338
- Add API to pause target and wait for debugger to be suspended
  - https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/339

**Comment by jonahgraham** [comment]
v1.0.1 of the adapter and the extension (#122) is now committed. 

This change didn't include the disassembly fix, so that means we will likely have v1.0.2 in the near future.

**Comment by jonahgraham** [comment]
Thanks @Luke-zhang-mchp for the contributions

**Comment by Luke-zhang-mchp** [comment]
Great! And thank you for all the open source work @jonahgraham.

**Pull request merged**
